### PR TITLE
Add dockerfile  for fonrtend react app

### PR DESCRIPTION
**Pull request by RINO-GAELICO**
This pull request introduces updates to the existing Dockerfile and adds a .env.example file. 

The Dockerfile has been modified to implement a two-stage build process. The first stage, referred to as the build stage, utilizes a lightweight Alpine-based Node.js image to install dependencies, copy source files, and build the React application. The second stage, known as the production stage, employs an Nginx Alpine image to serve the application generated in the previous stage. Additionally, the container is configured to expose port 5000 in accordance with the specified requirements.

Furthermore, a .env.example file has been added to provide a template for managing environment-specific variables, including the VITE_BACKEND_URL, ensuring that backend service URLs can be easily configured.

### CODE REVIEW

**Comment by sethumadhavan-k** [comment]
@RINO-GAELICO what is the use of APP_PORT and why you changed 8080 port to 5000 in Dockerfile

**Comment by RINO-GAELICO** [comment]
Hi @sethumadhavan-k , I removed APP_PORT from env file, added configuration of server PORT in `vite.config.js`, and modified nginx.conf to listen to port 5000.
I believe `EXPOSE 5000` in the `Dockerfile` is now redundant. I can remove it if you agree with that.

**Comment by sethumadhavan-k** [comment]
Hi @RINO-GAELICO, Tested the Dockerfile and it's working! Please remove your yarn.lock file.

**Comment by RINO-GAELICO** [comment]
Hi @sethumadhavan-k, I am glad it worked. I removed the `yarn.lock` file

**Review by sethumadhavan-k — APPROVED** [review]

**Pull request merged**
