### PR TITLE
Adjusts minimum length for title and description on Plugin and Bot Configuration pages

### PR DESCRIPTION
**Pull request by gabrilito1**
Reduce minimum length for title and description on Plugin and Bot Configuration pages

### CODE REVIEW

**Comment by sethumadhavan-k** [comment]
One task is pending.. please set minimum length for plug-in name also

**Comment by gabrilito1** [comment]
done

**Comment by ashmilhussain** [comment]
@gabrilito1  no minimum length watning showing for Plugin name , please see the screenhsot


Screenshot 2024-09-30 at 8 49 27 AM

**Comment by sethumadhavan-k** [comment]
@gabrilito1 Please join slack if you need any support : https://join.slack.com/t/theailounge/shared_invite/zt-2ogkrruyf-FPOHuPr5hdqXl34bDWjHjw

**Comment by gabrilito1** [comment]
see now guys

**Comment by ashmilhussain** [comment]
LGTM

**Pull request merged**
