### PR TITLE
REMOVED FINISH BUTTON

### PR DESCRIPTION
**Pull request by PartishtaP**
### KYE CHANGES

1) Removed any logic or UI elements related to the Finish button in the UI component that uses these API services, focused on the component where we have the form and button rendering.

2) Also ensured that the API methods (saveBotCapability, updateBotCapability, and deleteBotCapability) are still in use without relying on a Finish button

### CODE REVIEW

**Comment by ashmilhussain** [comment]
@PartishtaP  can you include a screenshot after running this, since im getting a error after running this

at same time i can see ther is some a new Save button added, which we are not intended to

**Comment by sethumadhavan-k** [comment]
@PartishtaP don't save anything in capacity service file (services/Capacity). Just remove the "Finish" Button in capacity tab(In bot configuration page)
Also include a screenshot

**Comment by sethumadhavan-k** [comment]
@PartishtaP  Could you provide an update on this PR?

**Comment by ashmilhussain** [comment]
Closing this issue as there has been no follow-up. It has been reassigned to another contributor

**Pull request closed without merging**
