### PR TITLE
Resolve x-axis misalignment and y-axis label overlap in Bar Chart #78.

### PR DESCRIPTION
**Pull request by mdnihal5**
pimage3
pimage2
pimage1

### CODE REVIEW

**Comment by agberoz** [comment]
@sethumadhavan-k , Please review

**Comment by ashmilhussain** [comment]
Did we tried putting a larger text as Legend ? like **San francisco**

**Comment by sethumadhavan-k** [comment]
@mdnihal5 still have the alignment in x axis , also don't change the chart title style
[
Screenshot 2024-10-18 at 6 18 17 PM
](url)

**Comment by sethumadhavan-k** [comment]
@mdnihal5 any update on this ?

**Comment by mdnihal5** [comment]
> @mdnihal5 any update on this ?

I'm working on a fix 
The alignment completely depends on no of bars(categories)

**Comment by sethumadhavan-k** [comment]
@mdnihal5 any updates on this ?

**Pull request closed without merging**
