### PR TITLE
Add placeholder and hint for URL input box on Website Plugin Configuaration Page

### PR DESCRIPTION
**Pull request by uchiha-vivek**
**Add placeholder and hint for URL input box on Website Plugin Configuaration Page**
**ISSUE 29**

**Changes Made**

1-) **Added placeholder to URL input box**
2-) **Included a Hint below the input box**
3-)**removed uvloop from requirements.txt **

raggenie

Please Review !

### CODE REVIEW

**Comment by sethumadhavan-k** [comment]
@uchiha-vivek no need to push config.yaml file,  also place the hint message along with url input otherwise it always shows in every connector

**Comment by uchiha-vivek** [comment]
> @uchiha-vivek no need to push config.yaml file, also place the hint message along with url input otherwise it always shows in every connector

@sethumadhavan-k  
1-) Ok i will remove the config.yaml file
2-)**also place the hint message along with url input otherwise it always shows in every connector** - i have doubt in this :
Like do i need to include hint message also  inside the placeholder  .
something like :    https://www.raggenie.com  include http or https in the URL

**Comment by sethumadhavan-k** [comment]
@uchiha-vivek better to place below the input component

**Comment by uchiha-vivek** [comment]
@sethumadhavan-k  
1-)Removed config.yaml
2-) Did conditional rendering for url input Hint  so that after generateConfig() is called it dont show up always with all connector.

I hope it solves the above problem .

**Comment by ashmilhussain** [comment]
@uchiha-vivek 

please conside this isse also on same PR , since it's related

https://github.com/sirocco-ventures/raggenie/issues/33

check sample code there mentioned by @agberoz

**Comment by uchiha-vivek** [comment]
> @uchiha-vivek
> 
> please conside this isse also on same PR , since it's related
> 
> #33
> 
> check sample code there mentioned by @agberoz

@ashmilhussain  Sure

**Comment by uchiha-vivek** [comment]
@ashmilhussain  uvloop issue fixed in the same pull request !

code changed : `uvloop==0.20.0; sys_platform != 'win32'`

**Comment by sethumadhavan-k** [comment]
@uchiha-vivek spelling mistake, not "int the url" , it is "in the url"

**Comment by ashmilhussain** [comment]
@uchiha-vivek great , once reviewed i will merge this

**Comment by uchiha-vivek** [comment]
@sethumadhavan-k  fixed the spelling error.

**Pull request merged**
